### ISSUE TITLE
[Intro to iOS] Project 3: Twitter

### ISSUE THREAD

**Issue by niazjalal** [niazjalal/ios_bootcamp_twitter#1]
Project completed with required stories mostly. -- Niaz

added readme and animated gif

/cc @thecodepath

**Comment by timothy1ee** [comment]
Hey Niaz, good work on this project. I noticed that you spent a lot of time on this project, what was the most time consuming part? Would love to get some feedback via email if you get a chance. Overall, things looked good, although looks like you still need some work on Auto Layout, and it would be good to tackle more optionals when you get a chance.
- API client and models look good. In production, there would be more validation to be robust to unexpected values, but in this homework it was fine to assume a well behaved API.
- TweetCell looks good, nice use of the property observer. You can also make the view properties private to fully encapsulate that class.
  - You have a bunch of Auto Layout warnings in the cell.
- ReplyViewController and ComposeViewController are pretty similar, I would consider combining.
- TweetsViewController, ComposeViewController, and TweetViewController looks good.
- If you tackled some of the optionals, you probably would have had custom protocols as well.

**Comment by niazjalal** [comment]
Completed.
